server:
  port: 8888

app:
  api-prefix: /api/v1

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: authservice
          uri: http://localhost:8080
          predicates:
            - Path=${app.api-prefix}/identity/**
          filters:
            - StripPrefix=2
        - id: profile-service
          uri: http://localhost:8081
          predicates:
            - Path=${app.api-prefix}/profile/users/**
          filters:
            - StripPrefix=2
        - id: chatbot
          uri: http://localhost:8082
          predicates:
            - Path=${app.api-prefix}/chatbot/**
          filters:
            - StripPrefix=2
        - id: appointment
          uri: http://localhost:8084
          predicates:
            - Path=${app.api-prefix}/appointment/**
          filters:
            - StripPrefix=2
        - id: notification
          uri: http://localhost:8085
          predicates:
            - Path=${app.api-prefix}/notification/**
          filters:
            - StripPrefix=2

